name: Build docker docker image

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  buildx:
    runs-on: ubuntu-latest

    env:
      DOCKER_REGISTRY: ghcr.io

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Check outputs
        run: echo ${{ steps.vars.outputs.sha_short }}

      - name: Lower Repository
        id: lower_repository
        uses: ASzc/change-string-case-action@v6
        with:
          string: ${{ github.repository }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ steps.lower_repository.outputs.lowercase }}:buildcache
          cache-to: type=registry,ref=${{ env.DOCKER_REGISTRY }}/${{ steps.lower_repository.outputs.lowercase }}:buildcache,mode=max
          pull: true
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ steps.lower_repository.outputs.lowercase }}:latest
            ${{ env.DOCKER_REGISTRY }}/${{ steps.lower_repository.outputs.lowercase }}:${{ steps.vars.outputs.sha_short }}
